version: "3.9"

services:
  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      MONGODB_URL: mongodb://mongo:27017/authPracticeTest
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
